### ISSUE TITLE
Yarn over NPM?

### ISSUE THREAD

**Issue by HonoriaShana** [ginkoid/bps#1]
**HOW DARE YOU USE YARN POOR NPM MUST FEEL SO BAD!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! OH MY LORD YOU BETRAYED NPM ;-;-;-;-;-;-;-;;-;-;-;-;-;;-;-;
![rip me](https://user-images.githubusercontent.com/33732069/36671574-07523e3a-1aca-11e8-9de3-8c21f406c9d9.jpg)
**

**Comment by HonoriaShana** [comment]
**_rip npm 2018_**

**Comment by ginkoid** [comment]
You may read about the benefits of yarn on [yarnpkg.com](https://yarnpkg.com/en/).
Additionally, package managers do not have feelings, nor can they rest in peace.

Closing as unproductive.
